name: california_housing
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip
  - pip:
    - -r requirements.txt
